### ISSUE TITLE
Variable description

### ISSUE THREAD

**Issue by stefankneifel** [rhoneyager/libicedb#13]
I admit I am not very familiar with hdf5 but from standard netcdf I am used to add variable description ("long_name"), units, and also comments. We could just use what we worked out in the Excel data structure table. I remember that most people agreed on it already, or? At least we should give some examples, how people can add these information.

But maybe this is already planned and you just wanted to start with the basic structure. I just wanted to show that I am actively looking into the files ;-)

**Comment by rhoneyager** [comment]
This can be easily added. When writing the shape file's variables (Shapes.cpp), there is code for each variable like:
```
tblPSEN = res->createTable<uint64_t>("particle_scattering_element_number",
				{ static_cast<size_t>(required->number_of_particle_scattering_elements) });
```
For a description, we can just add:
```
tblPSEN->writeAttribute<std::string>("long_name", { 1 }, { "description goes here" });
tblPSEN->writeAttribute<std::string>("units", { 1 }, { "units go here" });
tblPSEN->writeAttribute<std::string>("comments", { 1 }, { "comments go here "});
```

**Comment by rhoneyager** [comment]
Variable descriptions added.
