### ISSUE TITLE
particle_scattering_element_coordinates

### ISSUE THREAD

**Issue by stefankneifel** [rhoneyager/libicedb#14]
particle_scattering_element_coordinates should also have a dimension particle_constituent_number, right? In most cases this will be =1 (only ice) but shouldn't the dimension show up in the variable if I look at it in ncdump?

**Comment by rhoneyager** [comment]
There is then overlap between particle_scattering_element_coordinates [dims of: particle_scattering_element_number, 3, constituent_id] and the initial definition of  particle_scattering_element_composition [particle_scattering_element_number, particle_constituent_id].

I'm in favor of updating the schema to remove constituent_id as a dimension from particle_scattering_element_coordinates.

**Comment by rhoneyager** [comment]
For organization, I'm going to move all of the schema discussion to #30.
