### ISSUE TITLE
particle_single_constituent_name

### ISSUE THREAD

**Issue by stefankneifel** [rhoneyager/libicedb#15]
I don't really understand why we put the constituent name into a single attribute (particle_single_constituent_name) and not a variable as in the Excel table particle_constituent_name(particle_constituent_number)? Again, for just one constituent it doesn't really matter but if I have 2 or 3 I have to generate more and more new attributes instead of having one variables which contains them all.

**Comment by rhoneyager** [comment]
I haven't yet merged my improvements to the HDF5 backend; until then we can't easily write tables of strings. It's in progress.
