### ISSUE TITLE
particle_scattering_element_spacing missing

### ISSUE THREAD

**Issue by stefankneifel** [rhoneyager/libicedb#17]
We are missing the very important attribute: particle_scattering_element_spacing (inter dipole or inter sphere spacing). At least I couldn't find it in the GMM sample files Eugene sent around.

**Comment by DaveOri** [comment]
Actually that feature is already included via command line for DDA-type files (option --resolution). For GMM-like particles there is no inter-sphere spacing and sphere centers becomes a floating point coordinate; that information is replaced by the particle_scattering_element_radius table which is specific for each GMM sphere.

**Comment by rhoneyager** [comment]
I think that this variable needs to be renamed. For DDA, this is the lattice constant, which determines the resolution of the mesh. GMM-like particles do not have elements of mass aligned along a lattice. What we need is an attribute that describes the conversion of the scattering element coordinates into physical units... something like "length_scale_factor" (in meters).

**Comment by stefankneifel** [comment]
I like Ryan's idea! We just have to think how we can name that factor but being consistent with CF convention. Maybe something like particle_scattering_element_coordinates_conversion_factor  or _scale_factor??

**Comment by stefankneifel** [comment]
I just realized that in the original Table we decided to add this info just as an attribute. So CF naming is less of an issue...

**Comment by rhoneyager** [comment]
Still, the schema should be updated. particle_scattering_element_spacing is defined as "Physical spacing between adjacent grid points."

**Comment by rhoneyager** [comment]
5/17 discussion handled this. Changes are being tested in the l0-shape-changes branch.
