### ISSUE TITLE
Particle shape comparisons for 5/17 meeting

### ISSUE THREAD

**Issue by rhoneyager** [rhoneyager/libicedb#20]
@DaveOri, @stefankneifel, @eec3 
For the next meeting (Thursday), let's upload example files for each of our shape models to the FTP site.

**Comment by RobinEke** [comment]
My apologies. I have some shape-files with issues that would like to share, but I can't find any info on the FTP address or how to access it.

/Robin

**Comment by eec3** [comment]
Robin, I am forwarding on your email to Stefan and
Davide too as they too may be able to help with the
ftp. We should talk about organizing documentation
during our next Skype as we now have ScatPort
and GitHub IcdDB to build upon.
Eugene

----- Original Message -----

**Comment by DaveOri** [comment]
I have shared the credentials with robin on a private email. If anybody needs them again he/she is encouraged to ask me via email

**Comment by rhoneyager** [comment]
Due to the large number of changes to the code this week, I would suggest that we regenerate any older shape file results. This should make the comparison less confusing.

The 5/2018 reference version of the code is [here](https://github.com/rhoneyager/libicedb/releases/tag/2018.5). I'll fix any obvious bugs (segfaults, missing data), but any further changes to the shape structure format can be handled after the meeting.

It may be helpful if we have both ADDA/DDSCAT and icedb files uploaded to the FTP site.
