### ISSUE TITLE
Shape file filename extension

### ISSUE THREAD

**Issue by RobinEke** [rhoneyager/libicedb#24]
There seems to be a restriction on what filename extensions that are accepted (.dat, .shape).

My shape files use ".adda", hence I'm not able to import these (without changing the extension). Is there a reason for only specific extensions being allowed?

edit: ADDA output files use, ".geom", which does not seem to be supported as well. I think this extension should be supported at least.

**Comment by rhoneyager** [comment]
@MrFlask, I've updated the code to handle these cases.

Let me know if there are any problems with the matching.
