### ISSUE TITLE
Unit test functions

### ISSUE THREAD

**Issue by rhoneyager** [rhoneyager/libicedb#27]
The shape reading code needs automated testing programs. A set of valid shape files should be provided, and the results of parsing these shapes should be checked to ensure that they are read correctly.

**Comment by DaveOri** [comment]
I can code a test suite.
I would do it in python, but that of course would increase the number of dependencies of the overall software suite.
I see the boost library as a testing suite as well, we might prefer this approach to be more consistent

**Comment by rhoneyager** [comment]
I have an [old boost example, in an old repository](https://github.com/rhoneyager/rtmath/tree/master/rtmath/rtmath/tests). In particular, see [globals.cpp](https://github.com/rhoneyager/rtmath/blob/master/rtmath/rtmath/tests/globals.cpp), [globals.h](https://github.com/rhoneyager/rtmath/blob/master/rtmath/rtmath/tests/globals.h), [test.cpp](https://github.com/rhoneyager/rtmath/blob/master/rtmath/rtmath/tests/test.cpp), [test_units.cpp](https://github.com/rhoneyager/rtmath/blob/master/rtmath/rtmath/tests/test_units.cpp), and [test_shapefile.cpp](https://github.com/rhoneyager/rtmath/blob/master/rtmath/rtmath/tests/test_shapefile.cpp).

It would work rather well, particularly if we continue to depend on Boost.

**Comment by rhoneyager** [comment]
I have a sketch of the unit-testing implementation in the hdf-backend-improvements-1 branch. The shape testing can be a part of that.

**Comment by rhoneyager** [comment]
Several unit tests were added.
