### ISSUE TITLE
Mailing list server is not working

### ISSUE THREAD

**Issue by rhoneyager** [rhoneyager/libicedb#29]
I have tried to send two emails to the mailing list today, but they have not been sent to the group.

**Comment by DaveOri** [comment]
Apparently meteo-scattcode works,
meteo-scattdiscuss seems not reliable. I will report that to the IT.
My last attempt on meteo-scattdiscuss@uni-koeln.de succeded. Would you give it another try?

In any case when you send messages to the mailing list you should also receive your message in your mailbox. That should be a sufficient indication that your meassage has been sent.

**Comment by stefankneifel** [comment]
I checked the administrator page and looked at the archive of messages, here's a screenshot:
![image](https://user-images.githubusercontent.com/32867093/40224310-0db23900-5a86-11e8-9350-048d29e409cc.png)
It is weird: apparently Ryan's emails weren't received by the system... I also checked the membership list and Ryan is of course still in the list... @rhoneyager Ryan, can you give it another try and include me or Davide in cc? If it still doesn't work, we gonna contact our IT.
