### ISSUE TITLE
DDSCAT-type shape files of various versions

### ISSUE THREAD

**Issue by DaveOri** [rhoneyager/libicedb#6]
I have realized that my problems with importing shapefiles were due to an old version of ddscat shapefile I was using which requires a different number of header lines before start reading the coordinates.

ADDA scattering codes is able to ingest various shapefile formats transparently.
It might be good to have a look the same feature here

**Comment by rhoneyager** [comment]
See code comments on #11, apply changes and then feel free to merge.
