### ISSUE TITLE
Scattering element ordinal number

### ISSUE THREAD

**Issue by DaveOri** [rhoneyager/libicedb#7]
Scattering element number is always zero.
Shouldn't it be a progressive number?

**Comment by rhoneyager** [comment]
Right now, the code doesn't write the scattering element numbers when the numbers are trivial (1, 2, 3, 4, ...). Ordinarily, I would just consider it to be optional (and space-wasting) data. However, the scattering element number variable is also a dimension.

HDF5's Dimension Scale API suggests defining the variable but never writing data to it. The HDF5 developers have discussed adding support for sequential "fill values".

I'll fix it.
